from flask import Blueprint, render_template, request, redirect, url_for, flash, send_file
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.utils import secure_filename
from PyPDF2 import PdfReader
from .models import User, Job
from . import db
import os
from .skills_db import SKILLS_DB
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import io
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable
from reportlab.lib.styles import getSampleStyleSheet
main = Blueprint("main", __name__)


# -----------------------
# DOWNLOAD PDF REPORT
# -----------------------

@main.route("/download-report/<job>/<score>")
def download_report(job, score):

    buffer = io.BytesIO()

    styles = getSampleStyleSheet()

    elements = []

    matched_skills = request.args.getlist("matched")
    missing_skills = request.args.getlist("missing")

    elements.append(Paragraph("HireSmart Resume Analysis Report", styles['Title']))
    elements.append(Spacer(1,20))

    elements.append(Paragraph(f"<b>Recommended Job:</b> {job}", styles['Normal']))
    elements.append(Paragraph(f"<b>Match Score:</b> {score}%", styles['Normal']))

    elements.append(Spacer(1,20))

    elements.append(Paragraph("<b>Matched Skills</b>", styles['Heading3']))
    elements.append(ListFlowable([Paragraph(skill, styles['Normal']) for skill in matched_skills]))

    elements.append(Spacer(1,20))

    elements.append(Paragraph("<b>Missing Skills</b>", styles['Heading3']))
    elements.append(ListFlowable([Paragraph(skill, styles['Normal']) for skill in missing_skills]))

    elements.append(Spacer(1,30))

    elements.append(Paragraph("Generated by HireSmart AI Resume Analyzer", styles['Normal']))

    doc = SimpleDocTemplate(buffer, pagesize=letter)
    doc.build(elements)

    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name="resume_report.pdf",
        mimetype="application/pdf"
    )

# -----------------------
# EXTRACT SKILLS FROM TEXT
# -----------------------
def extract_skills(text):

    text = text.lower()
    found_skills = []

    all_skills = []

    for role in SKILLS_DB:
        for skill in SKILLS_DB[role]:
            all_skills.append(skill)

    all_skills = list(set(all_skills))

    for skill in all_skills:
        if skill in text:
            found_skills.append(skill)

    return list(set(found_skills))


# -----------------------
# HOME
# -----------------------
@main.route("/")
def home():
    return render_template("index.html")


# -----------------------
# REGISTER
# -----------------------
@main.route("/register", methods=["GET", "POST"])
def register():

    if request.method == "POST":

        name = request.form.get("name")
        email = request.form.get("email")
        password = request.form.get("password")

        existing_user = User.query.filter_by(email=email).first()

        if existing_user:
            flash("Email already registered")
            return redirect(url_for("main.register"))

        user = User(username=name, email=email)
        user.set_password(password)

        db.session.add(user)
        db.session.commit()

        flash("Registration successful")
        return redirect(url_for("main.login"))

    return render_template("register.html")


# -----------------------
# LOGIN
# -----------------------
@main.route("/login", methods=["GET", "POST"])
def login():

    if request.method == "POST":

        email = request.form.get("email")
        password = request.form.get("password")

        user = User.query.filter_by(email=email).first()

        if user and user.check_password(password):

            login_user(user)
            return redirect(url_for("main.dashboard"))

        flash("Invalid login")

    return render_template("login.html")


# -----------------------
# DASHBOARD
# -----------------------
@main.route("/dashboard")
@login_required
def dashboard():

    jobs = Job.query.all()

    return render_template(
        "dashboard.html",
        jobs=jobs,
        user=current_user
    )


# -----------------------
# UPLOAD RESUME
# -----------------------
@main.route("/upload/<int:job_id>", methods=["GET", "POST"])
@login_required
def upload(job_id):

    job = Job.query.get_or_404(job_id)

    if request.method == "POST":

        file = request.files["resume"]
        filename = secure_filename(file.filename)

        upload_folder = "uploads"

        if not os.path.exists(upload_folder):
            os.makedirs(upload_folder)

        filepath = os.path.join(upload_folder, filename)
        file.save(filepath)

        resume_text = ""

        # TXT
        if filename.endswith(".txt"):
            with open(filepath, "r", errors="ignore") as f:
                resume_text = f.read().lower()

        # PDF
        elif filename.endswith(".pdf"):
            reader = PdfReader(filepath)

            for page in reader.pages:
                text = page.extract_text()
                if text:
                    resume_text += text.lower()

        resume_skills = extract_skills(resume_text)

        job_title = job.title.lower()

        job_skills = []

        for role in SKILLS_DB:
            if role in job_title:
                job_skills = SKILLS_DB[role]

        if len(job_skills) == 0:
            job_skills = ["python", "flask", "html", "css", "sql"]

        matched_skills = []
        missing_skills = []

        for skill in job_skills:
            if skill in resume_skills:
                matched_skills.append(skill)
            else:
                missing_skills.append(skill)

        score = int((len(matched_skills) / len(job_skills)) * 100)

        all_jobs = Job.query.all()

        job_scores = []

        for j in all_jobs:

            job_text = (j.title + " " + j.description).lower()

            skills = extract_skills(job_text)

            if len(skills) == 0:
                continue

            matches = 0

            for s in skills:
                if s in resume_skills:
                    matches += 1

            temp_score = int((matches / len(skills)) * 100)

            job_scores.append({
                "job": j,
                "score": temp_score
            })

        job_scores = sorted(job_scores, key=lambda x: x["score"], reverse=True)

        top_jobs = job_scores[:3]

        resume_strength = "Beginner"

        if score >= 80:
            resume_strength = "Strong"
        elif score >= 50:
            resume_strength = "Average"
        else:
            resume_strength = "Weak"

        return render_template(
            "result.html",
            job=job,
            score=score,
            matched_skills=matched_skills,
            missing_skills=missing_skills,
            top_jobs=top_jobs,
            resume_strength=resume_strength
        )

    return render_template("upload_resume.html", job=job)


# -----------------------
# LOGOUT
# -----------------------
@main.route("/logout")
@login_required
def logout():

    logout_user()

    flash("Logged out")

    return redirect(url_for("main.login"))


# -----------------------
# ABOUT
# -----------------------
@main.route("/about")
def about():
    return render_template("about.html")


# -----------------------
# RESUME TIPS
# -----------------------
@main.route("/resume-tips")
def tips():
    return render_template("tips.html")


# -----------------------
# JOB DETAIL
# -----------------------
@main.route("/job/<int:id>")
def job_detail(id):

    job = Job.query.get_or_404(id)

    return render_template("job_detail.html", job=job)


# -----------------------
# PROFILE
# -----------------------
@main.route("/profile")
@login_required
def profile():

    return render_template("profile.html", user=current_user)